name: Java CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

#### JAVA VERSION ####

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x

#### Checkout jeometry ####
    - name: Checkout jeometry
      uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
        repository: ${{github.repository}}
        path: jeometry

#### MAVEN REPOSITORY CACHE ####
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

#### Build jeometry ####
    - name: Build jeometry
      run: mvn install
      working-directory: ./jeometry
