name: Release Build

on:
  push:
    tags:
    - '*'

jobs:
  release_build:
    runs-on: ubuntu-latest

    steps:

#### JAVA VERSION ####
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x

#### Maven settings ####
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{"id": "github", "url": "https://maven.pkg.github.com/${{github.repository}}"}]'
        servers: '[{ "id": "github", "username": "${{github.actor}}", "password": "${{secrets.GITHUB_TOKEN}}" }]'

#### Checkout ####
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
        repository: ${{github.repository}}

#### MAVEN REPOSITORY CACHE ####
    - name: Maven Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-tag-build-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-tag-build-

#### Deploy ####
    - name: Deploy
      run: mvn -B deploy -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{github.repository}}
