
CREATE TABLE "GEOMARK"."GMK_GEOMARK_GROUP_XREF"
 ("GEOMARK_GROUP_XREF_ID" VARCHAR(35) NOT NULL
 ,"GEOMARK_GROUP_ID" VARCHAR(35) NOT NULL
 ,"GEOMARK_ID" VARCHAR(35) NOT NULL
 ,"WHEN_CREATED" TIMESTAMP NOT NULL
 )
 
;

COMMENT ON TABLE "GEOMARK"."GMK_GEOMARK_GROUP_XREF" IS 'The GMK GEOMARK GROUP XREF is used to Construct a new reference to the GEOMARK POLY for a GEOMARK GROUP. When a geomark is in a group to it will not be automatically removed by the daily cleanup routine.'
;

COMMENT ON COLUMN "GEOMARK"."GMK_GEOMARK_GROUP_XREF"."GEOMARK_GROUP_XREF_ID" IS 'This is the unique key for the GMK GEOMARK GROUP XREF. The unique key contains the gx- prefix with a GUID generated id, for example gx-8e4f5974c5b5484ab4e50bc42d4c085b.'
;

COMMENT ON COLUMN "GEOMARK"."GMK_GEOMARK_GROUP_XREF"."GEOMARK_GROUP_ID" IS 'This is the unique key for the GEOMARK GROUP. The unique key contains the gg- prefix with a GUID generated id, for example gg-8e4f5974c5b5484ab4e50bc42d4c085b.'
;

COMMENT ON COLUMN "GEOMARK"."GMK_GEOMARK_GROUP_XREF"."GEOMARK_ID" IS 'This is the unique key for the GEOMARK POLY. The unique key contains the gm- prefix with a GUID generated id, for example gm-8e4f5974c5b5484ab4e50bc42d4c085b.'
;

COMMENT ON COLUMN "GEOMARK"."GMK_GEOMARK_GROUP_XREF"."WHEN_CREATED" IS 'This is the timestamp when the record was created.'
;


ALTER TABLE "GEOMARK"."GMK_GEOMARK_GROUP_XREF"
 ADD CONSTRAINT GMK_GGX_PK PRIMARY KEY 
  ("GEOMARK_GROUP_XREF_ID")
  
 
 
;


ALTER TABLE "GEOMARK"."GMK_GEOMARK_GROUP_XREF"
 ADD CONSTRAINT GMK_GGX_UK UNIQUE 
  ("GEOMARK_GROUP_XREF_ID"
  ,"GEOMARK_GROUP_ID")
  
 
 
;


ALTER TABLE "GEOMARK"."GMK_GEOMARK_GROUP_XREF" ADD CONSTRAINT
 GMK_GGX_GMK_G_FK FOREIGN KEY 
  ("GEOMARK_ID") REFERENCES "GEOMARK"."GMK_GEOMARK_POLY"
  ("GEOMARK_ID")
;


ALTER TABLE "GEOMARK"."GMK_GEOMARK_GROUP_XREF" ADD CONSTRAINT
 GMK_GGX_GMK_GG_FK FOREIGN KEY 
  ("GEOMARK_GROUP_ID") REFERENCES "GEOMARK"."GMK_GEOMARK_GROUPS"
  ("GEOMARK_GROUP_ID")
;


CREATE INDEX GMK_GGX_GMK_G_FK_I ON "GEOMARK"."GMK_GEOMARK_GROUP_XREF"
 ("GEOMARK_ID")
 
 
;


CREATE INDEX GMK_GGX_GMK_GG_FK_I ON "GEOMARK"."GMK_GEOMARK_GROUP_XREF"
 ("GEOMARK_GROUP_ID")
 
 
;

GRANT DELETE, INSERT, SELECT, UPDATE ON "GEOMARK"."GMK_GEOMARK_GROUP_XREF" TO GEOMARK_USER
;
