
CREATE TABLE "GEOMARK"."GMK_CONFIG_PROPERTIES"
 ("CONFIG_PROPERTY_ID" NUMERIC(5) NOT NULL
 ,"PROPERTY_NAME" VARCHAR(255) NOT NULL
 ,"VALUE" VARCHAR(4000)
 )

;

COMMENT ON TABLE "GEOMARK"."GMK_CONFIG_PROPERTIES" IS 'The CONFIG PROPERTY contains editable configuration properties which can be used to configure the PL;SQL and java code without requiring a re-delivery of the application.'
;

COMMENT ON COLUMN "GEOMARK"."GMK_CONFIG_PROPERTIES"."CONFIG_PROPERTY_ID" IS 'The CONFIG PROPERTY ID is a unique surrogate identifier for the object CONFIG PROPERTY.'
;

COMMENT ON COLUMN "GEOMARK"."GMK_CONFIG_PROPERTIES"."PROPERTY_NAME" IS 'This is the unique key for the CONFIG PROPERTY. The value is the name of the configuration property (e.g. geomarkConfig.maxGeomarkAgeDays).'
;

COMMENT ON COLUMN "GEOMARK"."GMK_CONFIG_PROPERTIES"."VALUE" IS 'This is the text value that the config property is to be set to.'
;


ALTER TABLE "GEOMARK"."GMK_CONFIG_PROPERTIES"
 ADD CONSTRAINT GMK_CP_PK PRIMARY KEY
  ("CONFIG_PROPERTY_ID")
;


CREATE SEQUENCE "GEOMARK"."GMK_CP_SEQ"
 NO MAXVALUE
 NO MINVALUE
 NO CYCLE
;

GRANT DELETE, INSERT, SELECT, UPDATE ON "GEOMARK"."GMK_CONFIG_PROPERTIES" TO GEOMARK_USER
;

GRANT USAGE ON "GEOMARK"."GMK_CP_SEQ" TO GEOMARK_USER
;
