SPOOL dba.log

PROMPT Creating Tablespace 'GEOMARK' 
CREATE TABLESPACE GEOMARK  
DATAFILE '&GEOMARK_DIR./geomark_tables01.dbf' SIZE 1000M
/
 
PROMPT Creating Tablespace 'GEOMARK_NDX' 
CREATE TABLESPACE GEOMARK_NDX  
DATAFILE '&GEOMARK_NDX_DIR./geomark_indexes01.dbf' SIZE 1000M
/

PROMPT Creating User 'GEOMARK'
CREATE USER GEOMARK IDENTIFIED BY &GEOMARK_PW.
  DEFAULT TABLESPACE GEOMARK
  QUOTA UNLIMITED ON GEOMARK
  QUOTA UNLIMITED ON GEOMARK_NDX
/

GRANT CREATE VIEW TO GEOMARK 
/

GRANT CREATE TABLE TO GEOMARK 
/

GRANT CREATE SEQUENCE TO GEOMARK 
/

GRANT CREATE ROLE TO GEOMARK 
/

GRANT CREATE TYPE TO GEOMARK 
/

GRANT CREATE PROCEDURE TO GEOMARK 
/

GRANT CREATE SESSION TO GEOMARK 
/

PROMPT Creating User 'PROXY_GEOMARK_WEB'
CREATE USER PROXY_GEOMARK_WEB IDENTIFIED BY &PROXY_GEOMARK_WEB_PW.
/
GRANT CREATE SESSION TO PROXY_GEOMARK_WEB 
/

PROMPT Creating Role 'GEOMARK_USER'
CREATE ROLE GEOMARK_USER NOT IDENTIFIED
/

GRANT GEOMARK_USER TO PROXY_GEOMARK_WEB 
/

@ogis_spatial_reference_systems.sql
