PROMPT Creating Table 'GMK_GEOMARK_POLY'
CREATE TABLE GMK_GEOMARK_POLY
 (GEOMARK_ID VARCHAR2(35) NOT NULL
 ,MIN_EXPIRY_DATE DATE NOT NULL
 ,EXPIRY_DATE DATE NOT NULL
 ,WHEN_CREATED TIMESTAMP NOT NULL
 ,GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL
 )
 TABLESPACE GEOMARK
/

COMMENT ON TABLE GMK_GEOMARK_POLY IS 'The oracle spatial layer GEOMARK POLY is non-multipart polygon feature that stores a GeoMark polygon registered with the GeoMark Web Service.'
/

COMMENT ON COLUMN GMK_GEOMARK_POLY.GEOMARK_ID IS 'This is the unique key for the GEOMARK POLY. The unique key contains the gm- prefix with a GUID generated id, for example gm-8e4f5974c5b5484ab4e50bc42d4c085b.'
/

COMMENT ON COLUMN GMK_GEOMARK_POLY.EXPIRY_DATE IS 'This is the date when the geomark will expire and be deleted if it is not part of a group.'
/

COMMENT ON COLUMN GMK_GEOMARK_POLY.WHEN_CREATED IS 'This is the timestamp when the record was created.'
/

COMMENT ON COLUMN GMK_GEOMARK_POLY.GEOMETRY IS 'This is the Oracle geometry POLYGON location of the GeoMark.'
/

PROMPT Creating Primary Key on 'GMK_GEOMARK_POLY'
ALTER TABLE GMK_GEOMARK_POLY
 ADD (CONSTRAINT GMK_G_PK PRIMARY KEY 
  (GEOMARK_ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE GEOMARK_NDX)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON GMK_GEOMARK_POLY TO GEOMARK_USER
/

INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('GMK_GEOMARK_POLY','GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', 263000, 1876000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', 356000, 1738000, 0.001)),3005);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES ('GEOMARK', 'GMK_GEOMARK_POLY','GEOMETRY', 'GEOMARK', 'GMK_GEOMARK_POLY',1000,2,1003005);
CREATE INDEX GMK_GP_SI ON GMK_GEOMARK_POLY(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=collection,sdo_indx_dims=2,tablespace=GEOMARK_NDX') PARALLEL;
