DECLARE
  CS_ID NUMBER := 3857;
  SRID NUMBER;
BEGIN
  SELECT
    SRID INTO SRID
  FROM
    OGIS_SPATIAL_REFERENCE_SYSTEMS
  WHERE
    SRID = 1000000 + CS_ID
  ;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO OGIS_SPATIAL_REFERENCE_SYSTEMS(
      SRID,
      AUTH_NAME,
      AUTH_SRID,
      SRTEXT,
      SRNUM
    ) VALUES (
      1000000 + CS_ID,
      'EPSG',
      CS_ID,
      (SELECT WKTEXT FROM MDSYS.SDO_CS_SRS WHERE SRID = CS_ID),
      CS_ID
    );
END;
/

DEFINE TABLE_NAME=POINT2
DEFINE GEOMETRY_TYPE=1
DEFINE LAYER_GTYPE=point
DEFINE AXIS_COUNT=2
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=POINT3
DEFINE GEOMETRY_TYPE=1
DEFINE LAYER_GTYPE=point
DEFINE AXIS_COUNT=3
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Z', -2500, 5000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=MULTI_POINT2
DEFINE GEOMETRY_TYPE=4
DEFINE LAYER_GTYPE=multipoint
DEFINE AXIS_COUNT=2
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=MULTI_POINT3
DEFINE GEOMETRY_TYPE=4
DEFINE LAYER_GTYPE=multipoint
DEFINE AXIS_COUNT=3
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Z', -2500, 5000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=LINESTRING2
DEFINE GEOMETRY_TYPE=2
DEFINE LAYER_GTYPE=line
DEFINE AXIS_COUNT=2
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=LINESTRING3
DEFINE GEOMETRY_TYPE=2
DEFINE LAYER_GTYPE=line
DEFINE AXIS_COUNT=3
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Z', -2500, 5000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=MULTI_LINESTRING2
DEFINE GEOMETRY_TYPE=5
DEFINE LAYER_GTYPE=multiline
DEFINE AXIS_COUNT=2
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=MULTI_LINESTRING3
DEFINE GEOMETRY_TYPE=5
DEFINE LAYER_GTYPE=multiline
DEFINE AXIS_COUNT=3
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Z', -2500, 5000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=POLYGON2
DEFINE GEOMETRY_TYPE=3
DEFINE LAYER_GTYPE=polygon
DEFINE AXIS_COUNT=2
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=POLYGON3
DEFINE GEOMETRY_TYPE=3
DEFINE LAYER_GTYPE=polygon
DEFINE AXIS_COUNT=3
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Z', -2500, 5000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=MULTI_POLYGON2
DEFINE GEOMETRY_TYPE=6
DEFINE LAYER_GTYPE=multipolygon
DEFINE AXIS_COUNT=2
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

DEFINE TABLE_NAME=MULTI_POLYGON3
DEFINE GEOMETRY_TYPE=6
DEFINE LAYER_GTYPE=multipolygon
DEFINE AXIS_COUNT=3
DEFINE DIM=MDSYS.SDO_DIM_ELEMENT('X', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Y', -20000000, 20000000, 0.001),MDSYS.SDO_DIM_ELEMENT('Z', -2500, 5000, 0.001)
CREATE TABLE &TABLE_NAME (
  ID NUMBER(10) NOT NULL,
  GEOMETRY MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT &TABLE_NAME.PK PRIMARY KEY (ID)
);
CREATE SEQUENCE &TABLE_NAME._SEQ;
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('&TABLE_NAME.','GEOMETRY',MDSYS.SDO_DIM_ARRAY(&DIM.),3857);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES( 'TEST_ORACLE','&TABLE_NAME.','GEOMETRY','TEST_ORACLE','&TABLE_NAME.',&GEOMETRY_TYPE,&AXIS_COUNT,1003857);
CREATE INDEX &TABLE_NAME._SI ON &TABLE_NAME(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=&LAYER_GTYPE.,sdo_indx_dims=2') PARALLEL;

COMMIT;
