name: Java CI

on:
  push:
    branches:
    - master

jobs:
  java_ci:
    runs-on: ubuntu-latest

#### JAVA VERSION ####

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x

#### Checkout geomark ####
    - name: Checkout geomark
      uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
        repository: ${{github.repository}}
        path: geomark

#### MAVEN REPOSITORY CACHE ####
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

#### Build geomark ####
    - name: Build geomark
      run: mvn install -B
      working-directory: ./geomark

#### Github Pages ####
    - name: Deploy Github Pages
      run: git push origin `git subtree split --prefix src/docs master`:gh-pages --force
      working-directory: ./geomark

